apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    environment: dev
    # Pod Security Standards - Baseline enforcement with Restricted warnings
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resource-quota
  namespace: development
spec:
  hard:
    requests.cpu: "4"        # Reduced from 50 to align with cluster capacity
    requests.memory: "8Gi"   # Reduced from 100Gi to align with cluster capacity
    limits.cpu: "6"          # Reduced from 50 to align with cluster capacity
    limits.memory: "12Gi"    # Reduced from 100Gi to align with cluster capacity
    pods: "30"               # Reduced from 100 to be more realistic
    services: "10"           # Reduced from 20 to be more realistic
    persistentvolumeclaims: "10"  # Reduced from 20 to be more realistic
    secrets: "20"            # Added reasonable limit
    configmaps: "20"         # Added reasonable limit
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
  namespace: development
spec:
  limits:
  - max:
      cpu: "2"        # Reduced from 8 to be more realistic for t3.medium
      memory: 4Gi     # Reduced from 16Gi to be more realistic
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: "500m"     # Reduced from 1 to be more realistic
      memory: 1Gi     # Kept same as it's reasonable
    defaultRequest:
      cpu: "250m"     # Reduced from 500m to be more realistic
      memory: 512Mi   # Kept same as it's reasonable
    type: Container
  - max:
      cpu: "4"        # Reduced from 16 to be more realistic for t3.medium
      memory: 8Gi     # Reduced from 32Gi to be more realistic
    min:
      cpu: 100m
      memory: 128Mi
    type: Pod
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dev-network-policy
  namespace: development
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from same namespace
  - from:
    - podSelector: {}
  egress:
  # Allow DNS
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
  # Allow traffic within namespace
  - to:
    - podSelector: {}
  # Allow egress to internet (for pulling images, API calls, etc.)
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
