apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
    environment: shared
    # Pod Security Standards - Baseline (for log processing)
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: logging-resource-quota
  namespace: logging
spec:
  hard:
    requests.cpu: "40"
    requests.memory: 80Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    pods: "100"
    services: "25"
    persistentvolumeclaims: "25"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: logging-limit-range
  namespace: logging
spec:
  limits:
  - max:
      cpu: "8"
      memory: 16Gi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: "1"
      memory: 2Gi
    type: Container
  - max:
      cpu: "16"
      memory: 32Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: Pod
