apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: production
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2  # Update with your region
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: monitoring
