version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - echo Installing Trivy for security scanning...
      - |
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | tee -a /etc/apt/sources.list.d/trivy.list
        apt-get update
        apt-get install -y trivy
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - |
        if [ "$IMAGE_TAG" = "COMMIT_HASH" ]; then
          IMAGE_TAG=$COMMIT_HASH
        else
          IMAGE_TAG=${IMAGE_TAG:-$COMMIT_HASH}
        fi
      - echo Build started on `date`
      - echo Building Docker image with tag $IMAGE_TAG...

  build:
    commands:
      - echo Building the Docker image...
      - cd 03-CICD-APP-DEPLOYMENT/sample-app
      - docker build -t $ECR_REPOSITORY_URI:latest .
      - docker tag $ECR_REPOSITORY_URI:latest $ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker tag $ECR_REPOSITORY_URI:latest $ECR_REPOSITORY_URI:$COMMIT_HASH

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Scanning image for vulnerabilities...
      - |
        trivy image --severity HIGH,CRITICAL --exit-code 0 $ECR_REPOSITORY_URI:latest || {
          echo "Security scan found HIGH or CRITICAL vulnerabilities!"
          echo "Continuing build - vulnerabilities will be addressed in future iterations."
        }
      - echo Security scan completed!
      - echo Pushing Docker images to ECR...
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker push $ECR_REPOSITORY_URI:$COMMIT_HASH
      - echo Docker images pushed successfully
      - echo Writing image definitions file...
      - printf '[{"name":"sample-app","imageUri":"%s"}]' $ECR_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Build complete! Image pushed with tags:"
      - echo "  - $IMAGE_TAG"
      - echo "  - $COMMIT_HASH"
      - echo ""
      - echo "Updating Helm values with new image tag..."
      - |
        # Navigate back to repo root for git operations
        cd ../..
        
        # Update CI/CD development values (nodejs-chart)
        sed -i "s|tag: \".*\"|tag: \"$IMAGE_TAG\"|g" 02-HELM-GITOPS/helm-charts/nodejs-chart/values/dev.yaml
        
        # Update CI/CD production values (optional - for auto-deploy to prod)
        # sed -i "s|tag: \".*\"|tag: \"$IMAGE_TAG\"|g" 02-HELM-GITOPS/helm-charts/nodejs-chart/values/prod.yaml
        
        echo "Helm values updated with tag: $IMAGE_TAG"
        
        # Commit and push the updated values to trigger ArgoCD sync
        git config --global user.email "codebuild@example.com"
        git config --global user.name "AWS CodeBuild"
        git add 02-HELM-GITOPS/helm-charts/nodejs-chart/values/dev.yaml
        git commit -m "Update CI/CD image tag to $IMAGE_TAG for app-cicd-dev deployment"
        
        # Configure git to use token for authentication
        git remote set-url origin https://$GITHUB_TOKEN@github.com/stevebowes/devops-projects.git
        git push origin main

artifacts:
  files:
    - imagedefinitions.json